### ISSUE TITLE
Preinstalled Image?

### ISSUE THREAD

**Issue by invrspace** [leihs/community#1]
Hi Guys,

if I remember right there was a OS Image with preinstalled Leihs available quite some time ago. Unfortunately I can't find it anymore. Could you help me out and tell me where to find it?

Thanks!

**Comment by eins78** [comment]
We dont offer such an OS image, but there is a template repository to quickly install a self-hosting leihs ("quick" if you're already familiar with linux und ansible): https://github.com/leihs/leihs-instance
